version: "3.3"
services:
  app:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - ${DC_APP_PORT}:${DC_APP_PORT}
    # since we have created custom network, we have to mention it here
    networks:
      - micro_service


# since this file will run separately for each service, docker will create different networks for each of them
# to prevent this and have one netwrok so all services can talk to each other, we use "network" keyword of docker-compose
networks:
  # this is the name of our network
  micro_service:
    external:
      name: micro_service


    # # default value of the docker network driver
    # driver: bridge
