
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3hPVEUwTURVeE5Gb1hEVE15TURreE5qRTBNRFV4TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFlWCldNT24zOUpPSjlLSlJ6Nk9rcmY5S0YvNUJIK2FwaHZqcHE1elF1WlZMT3hRcElxTFhscVJ0UStHYWk4QVNZVVgKWjY1RmIrem5MbkNVMjN6eGFYbGVYWm9qM0pqS0dDSXZ5MnRGL2laUFNhZE9YTm5WQWZqUnJ4NGdBVCtIeW1xOApYa0g0eklaV1lLOXo0V004QmtTZGZVWjdaK005MWlhSTNydGFoZnhHRFZ3SVEwVWlqZGVDaCswZlFsc25BNlBmCnN4OHY1V1ZPYkVNVjlCZ2V1RnN1U0dLUTRxY09Pa2NvNzk2cVMvZDY2eEo0SDg2QitqbVh5NWJibjd1QjBRT2gKOUlVWXlEWHNjeFJPRHFCQnVoTXZDMW5uYXJyRGp0SnBtV1FpU1Q4TC83YW5VVktCVW84amZXR3BnRXlkMm1DUQpOT3VYbHhUakhRT1JMYTdINjBFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJbXV1L1dYNCsxd0tQR0RLUXlMTHVrcFdLN0ZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRklKa0t2UWczNms3OUVTT0QvNQp6ek5kMXJRVTRZQ0JobEZVdTFlbU9OR0l6OGJDSUJsVnlVOFhDTDQzWDhnZE9lTHJkRGp4TG45U203emVPemJLCk4wVC9zQkszM3pLVm8yb3hYaVJvZ01EUHlCaU5HNTVuelFxNGNCZGdkUUE2KythQTNRam1aQXg0SkhlRFZJajYKTjgvb1R1Uk1WOVRkNjFIVmFzbCtwS25RWE5XQnlEbW5ZZTlKYWs5QzUxZmFuS2hEK1VtY2c3ak5hZlBrSUlxdwppV2wrYzlKY2dyS0dIdzBFbE5vYWd4Y0JNWUpyYS9jT1ppejg5Y3hESU9uYWJNNkcxT3pMdUVrR1V2a1UrbjZECnZGQlNFVEpmYUcyUVRjb2FFejkwUG9YK2txYzlOczhsRzhhTjJTRzdIelo5V3dIcU1mR0Mzd0JnSXpNQjJrd0YKZ0NVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://151d5b79-c429-40c4-ae94-0459ecabcb03.eu-central-1.linodelke.net:443
  name: lke73150

users:
- name: lke73150-cicd
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImEyZ21jMGhiR0haa1BibmFrSG1aQXdXTHo3ZkhyVjJqa0Ffd2NJSGJZQU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1taWNyb3NlcnZpY2UiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiY2ljZC1zZXJ2aWNlLXRva2VuLXB2bWtwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImNpY2Qtc2VydmljZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjA2NjYxOTRjLTE1MGEtNGQ5Yi1iODJhLTE5ZDVhZDNiYmM1NyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1taWNyb3NlcnZpY2U6Y2ljZC1zZXJ2aWNlIn0.RMtXnRgwMIQWhyKtwV3JU57UEpEGXQzDsVQ5Kz1BbtECl4XcWwIOmgGX6tpesq2yj_DPUWXIQTjOfQhYOop8hKYvp3ngBemRSZG8FsX3V24ysMvb-aWhG01VD_Qa3zlEg57KgXLYlUhE7evNzTloahChYBYtcDiw_O1yIalMN-DgHjDIAUDRlwWfo9Yptr5UJJK1icL13j3Smb0tMjWSpl4wmZHyMIL25rUmzFNPuTgvZfVSYPrWLP9ddOpUk64GRua8TJ6Y3H78NYPtvJLN-t_pksFuO0J88rVMABZLw7NYiI4qcXsu76NQ2LQei_RArFrYsCWX9b4Nq7OjrVA1fA
contexts:
- context:
    cluster: lke73150
    namespace: default
    user: lke73150-cicd
  name: lke73150-ctx

current-context: lke73150-ctx
