# we are using a typical kubernetes secret file for our secret for the prometheus alert-manager
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gmail-auth
  # we should mention it is in same namespace as prometheus-stack, otherwise we can't access it from alert config file
  namespace: monitoring
data:
  password: <BASE64-ENCODED-VALUE-OF-PASSWORD>
