-
  name: Am in an Adult or a Child
  hosts: localhost
  vars:
    age: 25
  tasks:
    - command: echo "I am a Child"
    # we don't put age var inside {{  }} because we don't have string here
      when: age < 18

    - command: echo "I am an Adult"
      when: age >= 18
