# sample ansible playbook

- 
  name: check out status of service and email if it is down
  hosts: localhost
  tasks:
    - command: service httpd status
      register: command_output
      # mail module sends emails
    - mail:
          to: Admins <system.Admins@company.com>
          subject: Service Alert
          body: 'Service {{ ansible_host }} is down'
      when: command_output.stdout.find('down') != -1