- name: Test Connectivity to servers
  hosts: web_servers, db-servers
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    ansible_user: <USERNAME>
  tasks:
    - ping:

- name: Install and configure mysql database
  hosts: db_servers
  become: yes
  become_method: sudo
  roles:
    - python
    - mysql_db

- name: Install and configure web servers
  hosts: web_servers
  become: yes
  become_method: sudo
  roles:
    - python
    - flask_web
